Installs functionally now. Requires Rsync.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
 ##Created by Edward "edge226" Tunnah.
 
+## Check for root! If the user is not running the script as root advise
+## that root is required to operate this script and then drop out. If
+## the script is run as root then continue.
+if [ "$EUID" != "0" ]; then
+    printf "error: This script must be run as root.\n"
+    exit 1
+fi
+
 ## check if the install.conf file exists and import it if it does.
 if [[ -f ./install.conf ]]
   ## This file is imported for the variables used in this file.
@@ -22,19 +30,20 @@ for type in "${install_array[@]}"
     eval "ref=\$$type"
     if [[ -d "$ref" ]]
       then
-      printf '\n%s %s\n\n' "Creating directory:" "$ref"
+      ## printf '\n%s %s\n\n' "Creating directory:" "$ref"
       mkdir -p "$ref"
     fi
-  printf '\n%s %s\n\n' "The type of type is:" "$type"
+  ## printf '\n%s %s\n\n' "The type of type is:" "$type"
   if [[ -d "$type" ]]
     then
     for file in ./"$type"/*
     do
-      printf '%s %s %s %s\n' "Adding file to source:" "$file" "for" "$ref"
+      ## printf '%s %s %s %s\n' "Adding file to source:" "$file" "for" "$ref"
       source+=( "$file" )
     done
   fi
   ## add installation stuff here.
+  rsync -rvplH "${source[@]}" "$ref/"
 unset source
 unset -n ref
 done
